services:
  backend:
    volumes:
      - ./backend:/app
    command: flask run --host=0.0.0.0
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_APP=app.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules  # para evitar conflito de node_modules entre host e container
    ports:
      - "5173:5173"
    command: sh -c "npm run dev -- --host"