services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - db
      - flyway

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_DB=notakeoutdb
      - POSTGRES_USER=notakeoutdb
      - POSTGRES_PASSWORD=notakeout2026
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  flyway:
    image: redgate/flyway:latest
    depends_on:
      - db
    volumes:
      - ./database/migrations:/flyway/migrations
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/notakeoutdb
      FLYWAY_USER: notakeoutdb
      FLYWAY_PASSWORD: notakeout2026
      FLYWAY_LOCATIONS: filesystem:/flyway/migrations
    command: migrate

volumes:
  db_data:
    driver: local
